[tool.poetry]
name = "hmtt"
version = "0.1.0"
description = ""
authors = ["newbee1905 <beenewminh@outlook.com>"]
license = "BSD V3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
